services:
  # This is the definition for your web service, now using Docker
  - type: web
    name: campus-pulse-app
    env: docker # The crucial change: tell Render to use Docker
    plan: free
    
    # We no longer need buildCommand or startCommand.
    # The Dockerfile handles all of this.
    
    # The environment variables section remains the same.
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campus-pulse-db
          property: internalUrl