services:
  # This is the definition for your PHP web service
  - type: web
    name: campus-pulse-app
    env: php
    plan: free
    buildCommand: "composer install" # Top-level build command
    startCommand: "heroku-php-apache2 ."
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campus-pulse-db
          property: internalUrl