services:
  # This is the definition for your PHP web service
  - type: web
    name: campus-pulse-app
    env: php
    plan: free
    
    # --- The Build & Start Commands Section ---
    # These must be nested like this.
    build:
      command: "composer install"
    startCommand: "heroku-php-apache2 ."

    # --- The Environment Variables Section ---
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campus-pulse-db
          property: internalUrl