services:
  # This is the name of the web service (the PHP/Apache server)
  - type: web
    name: campus-pulse-app
    env: php # Tell Render to use its native PHP environment
    plan: free
      command: "composer install"
    startCommand: "heroku-php-apache2 ."
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campus-pulse-db # This must match the name of the database on Render
          property: internalUrl